### ISSUE TITLE
![JS/Backend] Comment bug when using certain characters

### ISSUE THREAD

**Issue by ChaseDB** [UNA-CS455/SchedulingApp#45]
When using symbols, such as ' or " or `, the comment will not go to the database.

This is a sensitive issue, since we are dealing with the handling of allowing these characters to appear only literally in the string for the comment, but not be picked up by the relational database manager as the end of the comment and the start of the command space. Take care that you do not introduce an injection attack vulnerability:

https://en.wikipedia.org/wiki/SQL_injection#Mitigation

**Comment by jeclark9063** [comment]
Fixed with prepared statements
