### ISSUE TITLE
[UI] Place an "X" in the top right hand corner of the 'My Reservations' popup.

### ISSUE THREAD

**Issue by ChaseDB** [UNA-CS455/SchedulingApp#46]
The only way to close the My Reservations popup is to click outside anywhere. This is fine and preferred, but we should also place a "X" in the top right hand corner of the popup that also does this to ensure user-friendliness.

**Comment by dillonborden21** [comment]
Implemented a red X now on that popup with the same functionality. Visual appeal needs to be discussed.
