### ISSUE TITLE
[UI] Email notifications

### ISSUE THREAD

**Issue by ChaseDB** [UNA-CS455/SchedulingApp#48]
-Add a checkbox by or near the reserve [Room] button that will call the mail script if checked.
[x] send confirmation email

-Add a checkbox by or near the update room button on the settings page that will call the mail script and send mail to everyone who has a reservation in that room to alert them of the changes if checked
[x] notify affected individuals

**Comment by dillonborden21** [comment]
Enhancement to UI added. waiting for mail script to be finished.
